spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=true&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapperLocations: classpath:springboot/mapper/*Mapper.xml
server:
  port: 80
  servlet.context-path: /springbootanddao/
