spring:
  datasource:
    #url: jdbc:mysql://192.168.86.128:3306/test?useSSL=true&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/test?useSSL=true&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 180000
      connection-timeout: 30000
  thymeleaf:
    cache: false
#@MapperScan注解和mybatis.mapper-locations缺一不可，前者扫描dao接口，后者扫描接口实现的mapper文件
mybatis:
  mapperLocations: classpath:springboot/mapper/*Mapper.xml
server:
  port: 8080
  servlet.context-path: /springbootanddao/
